### PR TITLE
Support state-machines outside of machines

### PR DESCRIPTION
**Pull request by cfsnook**

### CODE REVIEW

**Comment by asiehsalehi** [comment]
thank you colin, accepted to be merged

**Review by asiehsalehi — DISMISSED** [review]
thank you Colin, accepted to be merged

**Review by tshoang — DISMISSED** [review]
Great

**Comment by cfsnook** [comment]
I have fixed the dependency problem. checks pass

**Comment by cfsnook** [comment]
I forgot to merge the reviewed part and added some more changes.
Please could you check and approve this again.
It is now ready for release

**Review by tshoang — APPROVED** [review]
Works for me.

**Pull request merged**
